# Generated by Django 4.0.2 on 2023-12-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_front', '0002_rename_emai_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='promotions',
            field=models.ManyToManyField(to='store_front.Promotion'),
        ),
    ]
